version: "3.8"

name: "balance"

services:
  postgres:
    image: postgres:15
    ports:
      - "${PG_PORT_HOST:-5444}:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  nodejs_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT_HOST:-5555}:${APP_PORT:-3000}"
      - "${APP_PORT_DEBUG_HOST:-9333}:${APP_PORT_DEBUG:-9229}"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - postgres
